
apiVersion: v1
kind: Namespace
metadata:
  name: auto-registry
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: auto-registry
  namespace: auto-registry
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: auto-registry
    spec:
      initContainers:
        - name: netra-init
          image: lookyan/netra-init:master
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 128Mi
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
      containers:
        - name: app
          image: lookyan/auto-registry:v1
          ports:
            - containerPort: 8090
        - command:
            - "sh"
            - "-c"
            - "netramesh --service-name ${POD_NAMESPACE}.$(echo ${POD_NAME} | sed -e 's/-[a-z0-9]*-[a-z0-9]*$//g')"
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: INSTANCE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: JAEGER_AGENT_HOST
              value: "jaeger-agent.default"
            - name: JAEGER_AGENT_PORT
              value: "6831"
            - name: JAEGER_SAMPLER_TYPE
              value: const
            - name: JAEGER_SAMPLER_PARAM
              value: "1"
            - name: NETRA_HTTP_PORTS
              value: "8090"
          image: lookyan/netra-sidecar:master
          imagePullPolicy: IfNotPresent
          name: netra-sidecar
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 3000Mi
          securityContext:
            privileged: true
            readOnlyRootFilesystem: false
            runAsUser: 1337

---
apiVersion: v1
kind: Service
metadata:
  name: auto-registry
  namespace: auto-registry
spec:
  selector:
    app: auto-registry
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090

---

apiVersion: v1
kind: Namespace
metadata:
  name: billing
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: billing
  namespace: billing
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: billing
    spec:
      initContainers:
        - name: netra-init
          image: lookyan/netra-init:master
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 128Mi
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
      containers:
        - name: app
          image: lookyan/billing:v1
          ports:
            - containerPort: 8090
        - command:
            - "sh"
            - "-c"
            - "netramesh --service-name ${POD_NAMESPACE}.$(echo ${POD_NAME} | sed -e 's/-[a-z0-9]*-[a-z0-9]*$//g')"
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: INSTANCE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: JAEGER_AGENT_HOST
              value: "jaeger-agent.default"
            - name: JAEGER_AGENT_PORT
              value: "6831"
            - name: JAEGER_SAMPLER_TYPE
              value: const
            - name: JAEGER_SAMPLER_PARAM
              value: "1"
            - name: NETRA_HTTP_PORTS
              value: "8090"
          image: lookyan/netra-sidecar:master
          imagePullPolicy: IfNotPresent
          name: netra-sidecar
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 3000Mi
          securityContext:
            privileged: true
            readOnlyRootFilesystem: false
            runAsUser: 1337

---
apiVersion: v1
kind: Service
metadata:
  name: billing
  namespace: billing
spec:
  selector:
    app: billing
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090

---

apiVersion: v1
kind: Namespace
metadata:
  name: auth
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: auth
  namespace: auth
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: auth
    spec:
      initContainers:
        - name: netra-init
          image: lookyan/netra-init:master
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 128Mi
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
      containers:
        - name: app
          image: lookyan/auth:v1
          ports:
            - containerPort: 8090
        - command:
            - "sh"
            - "-c"
            - "netramesh --service-name ${POD_NAMESPACE}.$(echo ${POD_NAME} | sed -e 's/-[a-z0-9]*-[a-z0-9]*$//g')"
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: INSTANCE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: JAEGER_AGENT_HOST
              value: "jaeger-agent.default"
            - name: JAEGER_AGENT_PORT
              value: "6831"
            - name: JAEGER_SAMPLER_TYPE
              value: const
            - name: JAEGER_SAMPLER_PARAM
              value: "1"
            - name: NETRA_HTTP_PORTS
              value: "8090"
          image: lookyan/netra-sidecar:master
          imagePullPolicy: IfNotPresent
          name: netra-sidecar
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 3000Mi
          securityContext:
            privileged: true
            readOnlyRootFilesystem: false
            runAsUser: 1337

---
apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: auth
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090

---

apiVersion: v1
kind: Namespace
metadata:
  name: api-gateway
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: api-gateway
  namespace: api-gateway
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      initContainers:
        - name: netra-init
          image: lookyan/netra-init:master
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 128Mi
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
      containers:
        - name: app
          image: lookyan/api-gateway:v1
          ports:
            - containerPort: 8090
        - command:
            - "sh"
            - "-c"
            - "netramesh --service-name ${POD_NAMESPACE}.$(echo ${POD_NAME} | sed -e 's/-[a-z0-9]*-[a-z0-9]*$//g')"
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: INSTANCE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: JAEGER_AGENT_HOST
              value: "jaeger-agent.default"
            - name: JAEGER_AGENT_PORT
              value: "6831"
            - name: JAEGER_SAMPLER_TYPE
              value: const
            - name: JAEGER_SAMPLER_PARAM
              value: "1"
            - name: NETRA_HTTP_PORTS
              value: "8090"
          image: lookyan/netra-sidecar:master
          imagePullPolicy: IfNotPresent
          name: netra-sidecar
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 3000Mi
          securityContext:
            privileged: true
            readOnlyRootFilesystem: false
            runAsUser: 1337

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090

---

apiVersion: v1
kind: Namespace
metadata:
  name: accounter
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: accounter
  namespace: accounter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: accounter
    spec:
      initContainers:
        - name: netra-init
          image: lookyan/netra-init:master
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 128Mi
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
      containers:
        - name: app
          image: lookyan/accounter:v1
          ports:
            - containerPort: 8090
        - command:
            - "sh"
            - "-c"
            - "netramesh --service-name ${POD_NAMESPACE}.$(echo ${POD_NAME} | sed -e 's/-[a-z0-9]*-[a-z0-9]*$//g')"
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: INSTANCE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: JAEGER_AGENT_HOST
              value: "jaeger-agent.default"
            - name: JAEGER_AGENT_PORT
              value: "6831"
            - name: JAEGER_SAMPLER_TYPE
              value: const
            - name: JAEGER_SAMPLER_PARAM
              value: "1"
            - name: NETRA_HTTP_PORTS
              value: "8090"
          image: lookyan/netra-sidecar:master
          imagePullPolicy: IfNotPresent
          name: netra-sidecar
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 3000Mi
          securityContext:
            privileged: true
            readOnlyRootFilesystem: false
            runAsUser: 1337

---
apiVersion: v1
kind: Service
metadata:
  name: accounter
  namespace: accounter
spec:
  selector:
    app: accounter
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090

---
